### ISSUE TITLE
Tutorials section is not clickable

### ISSUE THREAD

**Issue by skonikevrone** [dj-stripe/dj-stripe.github.io#1]
It's a little bit confusing to see references to blog and videos without any links.

Could you please add links to the resources in the list?

![2022-06-01_12-54-37](https://user-images.githubusercontent.com/76766665/171378628-8bd25378-1a3a-4a18-8f43-2d8cc5e717fa.png)

**Comment by kavdev** [comment]
@skonikevrone good catch.

@jleclanche is this as simple as pushing a PR to fix this section https://github.com/dj-stripe/dj-stripe.github.io/blob/gh-pages/index.html#L412? I haven't worked with pages before and I'm not sure how our tooling is set up for the site.

**Comment by kavdev** [comment]
After a google, I think these are the referenced blogs? @jleclanche please confirm if you're able

* https://www.saaspegasus.com/guides/django-stripe-integrate/
* https://ordinarycoders.com/blog/article/django-stripe-monthly-subscription (seems correct, but date listed does not match)
* https://kartaca.com/en/django-stripe-integration-using-dj-stripe/

I can't see myself ever finding "Sample Tutorial" in the videos section. We'll just remove that 😄

**Comment by magamig** [comment]
> @jleclanche is this as simple as pushing a PR to fix this section https://github.com/dj-stripe/dj-stripe.github.io/blob/gh-pages/index.html#L412? I haven't worked with pages before and I'm not sure how our tooling is set up for the site.

Just update the markdown file, and it will be automatically built and deployed to [dj-stripe.dev](https://dj-stripe.dev/)
