### ISSUE TITLE
In Dark mode the text color is dark

### ISSUE THREAD

**Issue by abe-101** [dj-stripe/dj-stripe.github.io#16]

**Comment by MosheSommers** [comment]
Is the intent that the `What is dj-stripe` header be white?
![Screenshot 2024-06-11 at 3 11 28 PM](https://github.com/dj-stripe/dj-stripe.github.io/assets/23648276/17cb248f-6477-47bc-9fbb-d5cb66144d6b)

**Comment by abe-101** [comment]
no

The issue is under the [Documentation](https://dj-stripe.dev/2.8/installation/)  tab
(sorry - wasn't clear about it)

**Comment by kavdev** [comment]
granted, those headers should also be white

**Comment by abe-101** [comment]
fixed in https://github.com/dj-stripe/dj-stripe.github.io/commit/fecd5eb28d3eca852b2156723cfd2657c62da2da
